# ── LLM provider: huggingface | grok | ollama ──
llm.provider=huggingface

# ── Hugging Face (free cloud) ──
# huggingface.api-key=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
huggingface.api-key=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
huggingface.model=zai-org/GLM-5:novita
huggingface.baseurl=https://router.huggingface.co

# ── Grok (xAI) cloud ──
#grok.api-key=xai-sosr0OccEqjhV6M448Wl9IApmjc8cwBGbe44j0MziWql0j9nTgi8RYV0sxmYoaz0ksepG09yE9RM4rx4
grok.api-key=##
grok.model=grok-3-mini-fast
grok.baseurl=https://api.x.ai

# ── Ollama (local fallback) ──
ollama.baseurl=http://localhost:11434
ollama.model=deepseek-r1:7b

server.port=80