package com.example.socialmedia_poc.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.Instant;

public class WallPost {
    @JsonProperty("post_id")
    private String postId;

    private String content;
    private String category;

    @JsonProperty("source")
    private PostSource source; // SEED or GENERATED

    @JsonProperty("meta_config")
    private MetaConfig metaConfig;

    @JsonProperty("generation_context")
    private SeedWithMeta.GenerationContext generationContext;

    @JsonProperty("created_at")
    private Instant createdAt;

    @JsonProperty("batch")
    private int batch; // 1 = initial seeds, 2 = first personalized, 3 = next, etc.

    public enum PostSource {
        SEED,       // From existing seed files
        GENERATED   // Generated by model based on interactions
    }

    public WallPost() {
        this.createdAt = Instant.now();
    }

    // Convert from SeedWithMeta
    public static WallPost fromSeed(SeedWithMeta seed, int batch) {
        WallPost post = new WallPost();
        post.setPostId(seed.getSeedId());
        post.setContent(seed.getContent());
        post.setCategory(seed.getCategory());
        post.setSource(PostSource.SEED);
        post.setMetaConfig(seed.getMetaConfig());
        post.setGenerationContext(seed.getGenerationContext());
        post.setBatch(batch);
        return post;
    }

    public static WallPost fromGenerated(SeedWithMeta seed, int batch) {
        WallPost post = fromSeed(seed, batch);
        post.setSource(PostSource.GENERATED);
        return post;
    }

    // Getters and Setters
    public String getPostId() { return postId; }
    public void setPostId(String postId) { this.postId = postId; }

    public String getContent() { return content; }
    public void setContent(String content) { this.content = content; }

    public String getCategory() { return category; }
    public void setCategory(String category) { this.category = category; }

    public PostSource getSource() { return source; }
    public void setSource(PostSource source) { this.source = source; }

    public MetaConfig getMetaConfig() { return metaConfig; }
    public void setMetaConfig(MetaConfig metaConfig) { this.metaConfig = metaConfig; }

    public SeedWithMeta.GenerationContext getGenerationContext() { return generationContext; }
    public void setGenerationContext(SeedWithMeta.GenerationContext generationContext) { this.generationContext = generationContext; }

    public Instant getCreatedAt() { return createdAt; }
    public void setCreatedAt(Instant createdAt) { this.createdAt = createdAt; }

    public int getBatch() { return batch; }
    public void setBatch(int batch) { this.batch = batch; }
}
